### PR TITLE
Upgrade all the things

### PR DESCRIPTION
**Pull request by benlovell**
Bumps rails, mongoid and other dependencies to the latest/greatest.

Check the individual commit messages for details.

Trello: https://trello.com/c/kyf65IN1

### CODE REVIEW

**Comment by benlovell** [comment]
@alphagov/team-gov-uk-core-formats-and-publishing

**Comment by benilovj** [comment]
LGTM :+1: , but maybe someone else can give it a quick once-over before merging...

**Comment by boffbowsh** [comment]
Can you add `govuk-lint` in diff mode please?

**Comment by benlovell** [comment]
I'll get rid of the needless coverage as well.

**Pull request merged**
