### PR TITLE
Remove search from Maslow

### PR DESCRIPTION
**Pull request by alexmuller**
Maslow is running on a super old version of Elasticsearch (0.90). It's also soon going to be the only thing running on that old Elasticsearch cluster.

I've removed the search functionality because I suspect that nobody is using it, and it's the most simple way to allow us to remove the old Elasticsearch cluster and stop spending money on it.

### CODE REVIEW

**Comment by boffbowsh** [comment]
Maybe rather than doing this we can look at using Mongo to service the search queries, which would mean a change in need api. It does look like it's rarely used, so I think the traffic to MongoDB should be low enough for it to service search requests without causing problems.

**Comment by boffbowsh** [comment]
...having said that, I'm ok with this technically. I'm assuming there will be a follow up PR in need api to remove the functionality completely and remove the dependency on ES. Core own Maslow, so talk to Shilpa about whether we can remove search or not.

**Comment by sihugh** [comment]
To make it clear, Murray's tried a different approach to this in [the referenced PR](https://github.com/alphagov/govuk_need_api/issues/106) above, which replaces the ES behaviour with Mongo.

**Comment by alexmuller** [comment]
We're going to reduce this Elasticsearch cluster to one machine for now and then the content tools team are going to do some proper work on this in the coming weeks/months.

**Pull request closed without merging**
