### PR TITLE
Switch default branch to main

### PR DESCRIPTION
**Pull request by thomasleese**

### CODE REVIEW

**Review by kevindew — APPROVED** [review]
Nice 🤞

I guess it’s worth opening the jenkinslib branch as a PR

**Comment by thomasleese** [comment]
> I guess it’s worth opening the jenkinslib branch as a PR

Yeah, I'm going to spend a little bit more time investigating how we can auto-detect the default branch, but I'd like to merge this PR in first to check the `main` branch builds and a release tag is created.

If it works I'm happy to open your branch as a PR and then I can work on the auto-detection as a later PR, or I can try working on top of your branch and merge it all in as one PR, what would you prefer?

**Comment by kevindew** [comment]
> > I guess it’s worth opening the jenkinslib branch as a PR
> 
> Yeah, I'm going to spend a little bit more time investigating how we can auto-detect the default branch, but I'd like to merge this PR in first to check the `main` branch builds and a release tag is created.
> 
> If it works I'm happy to open your branch as a PR and then I can work on the auto-detection as a later PR, or I can try working on top of your branch and merge it all in as one PR, what would you prefer?

Oh yes feel free to merge this, and sorry I meant open the PR for visibility rather than because it's ready to merge - so a draft PR. It'd be awesome if you worked out the auto-detection 👍

**Comment by kevindew** [comment]
> > > I guess it’s worth opening the jenkinslib branch as a PR
> > 
> > 
> > Yeah, I'm going to spend a little bit more time investigating how we can auto-detect the default branch, but I'd like to merge this PR in first to check the `main` branch builds and a release tag is created.
> > If it works I'm happy to open your branch as a PR and then I can work on the auto-detection as a later PR, or I can try working on top of your branch and merge it all in as one PR, what would you prefer?
> 
> Oh yes feel free to merge this, and sorry I meant open the PR for visibility rather than because it's ready to merge - so a draft PR. It'd be awesome if you worked out the auto-detection 👍

It's here: https://github.com/alphagov/govuk-jenkinslib/pull/84 - let me know if you want to chat through any ideas. I somewhat wonder if we can just change the conditional on https://github.com/alphagov/govuk-jenkinslib/blob/d5deab4438d803954ef13f94a2cfa528290932d2/vars/govuk.groovy#L330 to be `master || main` or get rid of it altogether and just detect post clone.

**Pull request merged**
